# -*- coding: utf-8 -*-
"""visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pJpLZBF2VJC231vhplgFJ6CZR1xdvrdx
"""

import pandas as pd

# reading the database
data = pd.read_csv(r'C:\Users\HP\Downloads\crimes.csv')
  
# printing the top 10 rows
print(data.head(10))

#pip install matplotlib

import pandas as pd
import matplotlib.pyplot as plt


# reading the database
data = pd.read_csv(r'C:\Users\HP\Downloads\crimes.csv')

# Scatter plot with day against tip
plt.scatter(data['YEAR'], data['DISTRICT'])

# Adding Title to the Plot
plt.title("Scatter Plot")

# Setting the X and Y labels
plt.xlabel('YEAR')
plt.ylabel('DISTRICT')

plt.show()

#SCATTER PLOT

# reading the database
data = pd.read_csv(r'C:\Users\HP\Downloads\crimes.csv')

# Scatter plot with day against DISTRICT
plt.plot(data['DISTRICT'])
plt.plot(data['YEAR'])

# Adding Title to the Plot
plt.title("Scatter Plot")

# Setting the X and Y labels
plt.xlabel('YEAR')
plt.ylabel('DISTRICT')

plt.show()

#BAR CHART

import pandas as pd
import matplotlib.pyplot as plt

# reading the database
data = pd.read_csv(r'C:\Users\HP\Downloads\crimes.csv')

# Bar chart with year against district
plt.bar(data['YEAR'], data['DISTRICT'])

plt.title("Bar Chart")

# Setting the X and Y labels
plt.xlabel('YEAR')
plt.ylabel('DISTRICT')

# Adding the legends
plt.show()

#HISTOGRAM

import pandas as pd
import matplotlib.pyplot as plt

# reading the database
data = pd.read_csv(r'C:\Users\HP\Downloads\crimes.csv')

# histogram of STATES/UT
plt.hist(data['STATE/UT'])

plt.title("Histogram")

# Adding the legends
plt.show()

#pip install seaborn

# importing packages
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd


# reading the database
data = pd.read_csv(r'C:\Users\HP\Downloads\crimes.csv')

# draw lineplot
sns.lineplot(x="STATE/UT", y="DISTRICT", data=data)

# setting the title using Matplotlib
plt.title('Title using Matplotlib Function')

plt.show()

#SCATTER PLOT

# reading the database
data = pd.read_csv(r'C:\Users\HP\Downloads\crimes.csv')

sns.scatterplot(x='YEAR', y='DISTRICT', data=data,)
plt.show()

#SCATTER PLOT

# reading the database
data = pd.read_csv(r'C:\Users\HP\Downloads\crimes.csv')

sns.scatterplot(x='DISTRICT', y='YEAR', data=data,
                hue='YEAR')
plt.show()

#LINE PLOT

# reading the database
data = pd.read_csv(r'C:\Users\HP\Downloads\crimes.csv')

sns.lineplot(x='DISTRICT', y='YEAR', data=data)
plt.show()

#BAR PLOT


# reading the database
data = pd.read_csv(r'C:\Users\HP\Downloads\crimes.csv')

sns.barplot(x='DISTRICT',y='YEAR', data=data,
            hue='STATE/UT')

plt.show()

#HISTOPLOT

# reading the database
data = pd.read_csv(r'C:\Users\HP\Downloads\crimes.csv')

sns.histplot(x='STATE/UT', data=data, kde=True, hue='YEAR')

plt.show()

#pip install plotly

#SCATTER PLOT

import plotly.express as px
import pandas as pd

# reading the database
data = pd.read_csv(r'C:\Users\HP\Downloads\crimes.csv')

# plotting the scatter chart
fig = px.scatter(data, x="DISTRICT", y="YEAR", color='STATE/UT')

# showing the plot
fig.show()

#LINE PLOT

import plotly.express as px
import pandas as pd

# reading the database
data = pd.read_csv(r'C:\Users\HP\Downloads\crimes.csv')

# plotting the scatter chart
fig = px.line(data, y='YEAR', color='DISTRICT')

# showing the plot
fig.show()

#BAR CHART

import plotly.express as px
import pandas as pd

# reading the database
data = pd.read_csv(r'C:\Users\HP\Downloads\crimes.csv')

# plotting the scatter chart
fig = px.bar(data, x='YEAR', y='STATE/UT', color='DISTRICT')

# showing the plot
fig.show()

#HISTOGRAM

import plotly.express as px
import pandas as pd

# reading the database
data = pd.read_csv(r'C:\Users\HP\Downloads\crimes.csv')

# plotting the scatter chart
fig = px.histogram(data, x='STATE/UT', color='YEAR')

# showing the plot
fig.show()
